title: jresendiz27
email: jresendiz27@gmail..com
description: >- 
  Personal blog, just for nerding stuff
url: "http://jresendiz27.github.io"
twitter_username: jresendiz27
github_username:  jresendiz27

timezone: America/Mexico_City
permalink: /blog/:year/:month/:day/:title
paginate: 2
paginate_path: "/blog/page:num/"
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
highlighter: rouge